module.exports = {
  "ALIVE_IMG": "",
  "FOOT": "𓆩❤𓆪👨💓👩𝘾𝙃𝙐𝙕𝙕𝘼𝘼𓆩❤𓆪👨💓👩",
  "PREFIX": ".",
  "AUTO_READ_STATUS": "true",
  "MODE": "public",
  "BOT_NUMBER": "923057092048",
  "OMDB_API_KEY": "76cb7f39",
  "READ_CMD": "false",
  "AUTO_VOICE": "true",
  "ANTI_BAD": "warn",
  "ANTI_BOT": "true",
  "ANTI_CALL": "true",
  "ANTI_LINK": "warn",
  "ANTI_PHOTO": "false",
  "ANTI_STICKER": "false",
  "ANTI_DELETE": "true",
  "DELETEMSGSENDTO": "923253980306",
  "ALWAYS_ONLINE": "true",
  "MOROCCO_BLOCK": "false",
  "OWNER_NAME": "AS CHUZZA CHUZZII",
  "OWNER_NUMBER": "923253980306",
  "AUTO_BIO": "true",
  "AUTO_TYPING": "true",
  "AUTO_RECORDING": "true",
  "WARN_COUNT": "3",
};
